config/routes.rb
Rails.application.routes.draw do
  resources :jweets do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jweet.rb
class Jweet < ApplicationRecord
  validates :content, presence: true
  validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jweets_controller.rb
class JweetsController < ApplicationController
  before_action :set_jweet, only: [:show, :edit, :update, :destroy]
  def index
    @jweets = Jweet.all
  end
  def new
    @jweet = Jweet.new
  end
  def create
    @jweet = Jweet.new(jweet_params)
    if params[:back]
      render :new
    else
      if @jweet.save
        redirect_to jweets_path, notice: "Created new Jweet!"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @jweet.update(jweet_params)
      redirect_to jweet_path, notice: "edited your post"
    else
      render :edit
    end
  end
  def destroy
    @jweet.destroy
    redirect_to jweets_path, notice:"Deleted your post"
  end
  def confirm
    @jweet = Jweet.new(jweet_params)
    render :new if @jweet.invalid?
  end
  private
  def jweet_params
    params.require(:jweet).permit(:content)
  end
  def set_jweet
    @jweet = Jweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jweets_helper.rb
module JweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_jweets_path
    elsif action_name == 'edit'
      jweet_path
    end
  end
end

app/views/jweets/_form.html.erb
<%= form_with(model: @jweet, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @jweet.errors.any? %>
    <div id="error_explanation">
      <h2 id="error_msg"><%= @jweet.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @jweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li><br>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="jweet_content">
    <div>
      <%= form.label :content %>
    </div>
    <div>
      <%= form.text_area :content, size: "20x7", maxlength: 150 %>
    </div>
    <%= form.submit %>
    <br>
    <%= link_to 'Back to index page', jweets_path %>
  </div>
<% end %>

app/views/jweets/confirm.html.erb
<body>
  <header>
    <h1 class="title">Jweets</h1>
    <ul>
      <li><%= link_to 'new Jweet', new_jweet_path %></li>
      <li><a href="#">account</a></li>
      <li><a href="#">setting</a></li>
    </ul>
  </header>
  <div class="jweet_content">
    <h2>Confirm your post below</h2>
    <%= form_with(model: @jweet, local: true) do |form| %>
    <%= form.hidden_field :content %>
    <p>Content:<%= @jweet.content %></p>
    <%= form.submit  "submit your Jweet" %>
    <br>
    <%= form.submit "Back", name: 'back' %>
    <% end %>
    <%= link_to 'Back to index page', jweets_path %>
  </div>
  <footer>
    <p>Jweets! by TonbiNeko.</p>
  </footer>
</body>

app/views/jweets/edit.html.erb
<header>
  <h1 class="title">Jweets</h1>
  <ul>
    <li><%= link_to 'new Jweet', new_jweet_path %></li>
    <li><a href="#">account</a></li>
    <li><a href="#">setting</a></li>
  </ul>
</header>
<h2>Edit Jweet!</h2>
<%= render 'form' %>
<footer>
  <p>Jweets! by TonbiNeko.</p>
</footer>

app/views/jweets/index.html.erb
<body>
  <header>
    <h1 class="title">Jweets</h1>
    <ul>
      <li><%= link_to 'new Jweet', new_jweet_path %></li>
      <li><a href="#">account</a></li>
      <li><a href="#">setting</a></li>
    </ul>
    </header>
    <div id=notice>
      <%= notice %>
    </div>
    <table>
      <tr>
        <th>Contents</th>
      </tr>
      <% @jweets.each do |jweet| %>
      <tr>
        <td class="menu"><%= jweet.content %></td>
      </tr>
      <tr>
        <td><%= link_to '投稿確認', jweet_path(jweet.id) %></td>
      </tr>
      <tr>
        <td><%= link_to '編集', edit_jweet_path(jweet.id) %></td>
      </tr>
      <tr>
        <td><%= link_to '削除', jweet_path(jweet.id), method: :delete,data: { confirm: 'Are you sure to delete this post?' } %></td>
      </tr>
      <% end %>
    </table>
  <footer>
    <p>Jweets! by TonbiNeko.</p>
  </footer>
</body>

app/views/jweets/new.html.erb
<header>
<h1 class="title">Jweets</h1>
<ul>
  <li><%= link_to 'new Jweet', new_jweet_path %></li>
  <li><a href="#">account</a></li>
  <li><a href="#">setting</a></li>
</ul>
</header>
<h2>New Jweet!</h2>
<%= render 'form' %>
<footer>
  <p>Jweets! by TonbiNeko.</p>
</footer>

app/views/jweets/show.html.erb
<body>
  <header>
    <h1 class="title">Jweets</h1>
    <ul>
      <li><%= link_to 'new Jweet', new_jweet_path %></li>
      <li><a href="#">account</a></li>
      <li><a href="#">setting</a></li>
    </ul>
  </header>
  <div class="jweet_content">
    <h2>Content</h2>
    <br>
    <p><%= @jweet.content %></p>
    <%= link_to 'Back to index page', jweets_path %>
  </div>
  <footer>
    <p>Jweets! by TonbiNeko.</p>
  </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>